# Generated by Django 5.0.1 on 2026-04-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productoimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
