# Generated by Django 5.0.1 on 2026-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'QR'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
    ]
