# Generated by Django 5.0.1 on 2026-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_creado_venta_fecha_venta_estado_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='notificacion_cliente_vista',
            field=models.BooleanField(default=False),
        ),
    ]
