# Generated by Django 5.0.1 on 2026-04-23 12:54

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_proveedor_compraproveedor_detallecompraproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraproveedor',
            options={},
        ),
        migrations.RemoveField(
            model_name='compraproveedor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='compraproveedor',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='compraproveedor',
            name='numero_compra',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='fecha_compra',
            field=models.DateField(default=datetime.date(2026, 4, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='referencia_libre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='compraproveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('NOTA_VENTA', 'Nota de venta'), ('RECIBO', 'Recibo'), ('REFERENCIA', 'Referencia libre')], default='REFERENCIA', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='descripcion_base',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='producto_codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='producto_marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='producto_modelo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='producto_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='detallecompraproveedor',
            name='tipo_producto',
            field=models.CharField(choices=[('celular', 'Celular'), ('accesorio', 'Accesorio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_referencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('celular', 'Celular'), ('accesorio', 'Accesorio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='documento_ref',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], default='EMPRESA', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compraproveedor',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallecompraproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_compra', to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='DevolucionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('enviada', 'Enviada'), ('cerrada', 'Cerrada')], default='registrada', max_length=20)),
                ('fecha_devolucion', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='tienda.compraproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_proveedor', to='tienda.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='tienda.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('motivo', models.CharField(max_length=200)),
                ('stock_anterior', models.PositiveIntegerField(default=0)),
                ('stock_nuevo', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='tienda.compraproveedor')),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='tienda.devolucionproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='tienda.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReclamoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('fecha_reclamo', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='tienda.compraproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos_proveedor', to='tienda.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='tienda.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devolucionproveedor',
            name='reclamo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion', to='tienda.reclamoproveedor'),
        ),
    ]
