# Generated by Django 5.0.1 on 2026-05-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_compraproveedor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(max_length=40, unique=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_cita', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones_cliente', models.TextField(blank=True)),
                ('observaciones_revision', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('stock_restaurado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_cliente', to='tienda.cliente')),
                ('detalle_venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion_cliente', to='tienda.detalleventa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_cliente_revisadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_cliente', to='tienda.venta')),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
